# Generated by Django 5.0.4 on 2024-05-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0003_spotifysong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_pace', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadence.playlist')),
            ],
            options={
                'db_table': 'runs',
            },
        ),
    ]
