# Generated by Django 5.0.4 on 2024-05-03 14:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('real_pace', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('real_distance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('real_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadence.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recorded_runs',
            },
        ),
    ]
