# Generated by Django 5.0.4 on 2024-05-03 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0008_badge_earnedbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadence.plan')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadence.run')),
            ],
            options={
                'db_table': 'plan_runs',
            },
        ),
    ]
