# Generated by Django 5.0.4 on 2024-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0010_favoriteplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='avg_pace',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(),
        ),
    ]
