# Generated by Django 5.0.4 on 2024-05-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0011_alter_run_avg_pace_alter_run_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteplaylist',
            old_name='Playlist',
            new_name='playlist',
        ),
    ]
