# Generated by Django 5.0.4 on 2024-05-07 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0013_alter_recordedrun_real_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='segment',
            name='duration',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='segment',
            name='pace',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
