# Generated by Django 5.0.4 on 2024-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0014_alter_segment_distance_alter_segment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
