# Generated by Django 5.0.4 on 2024-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0015_userprofile_cover_photo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='level',
            field=models.CharField(default='beginner', max_length=255),
        ),
    ]
