# Generated by Django 5.0.4 on 2024-05-15 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0016_playlist_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='distance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
