# Generated by Django 5.0.4 on 2024-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0017_plan_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
