# Generated by Django 5.0.4 on 2024-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0018_playlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
